# ndarray array

In [1]:
import numpy as np

In [2]:
A = np.array([1, 2, 3]) # default generator, which converts lists (or other objects) into an ndarray array
A = np.zeros((2, 3)) # array of 0s with dimensions 2x3
B = np.ones((2, 3)) # array of 1s with dimensions 2x3
C = np.random.randn(2, 3) # random array (normal distribution) with dimensions 2x3
D = np.random.rand(2, 3) # random array (uniform distribution)
 
E = np.random.randint(0, 10, [2, 3]) # array of random integers from 0 to 10 and of dimension 2x3

In [3]:
A = np.ones((2, 3), dtype=np.float16) # define the type and the place to occupy on the memory
B = np.eye(4, dtype=np.bool) # create identity matrix and convert elements to type bool.

<ipython-input-3-aee19ee7a8dc>:2: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  B = np.eye(4, dtype=np.bool) # create identity matrix and convert elements to type bool.


In [4]:
A = np.linspace(1,10, 10)
B = np.arange(0, 10, 10)

In [5]:
A

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
B

array([0])

##  Important Attributes:
- size
- shape

In [7]:
A = np.zeros((2, 3)) # creating an array of shape (2, 3)
 
print(A.size) # the number of elements in array A
print(A.shape) # the dimensions of array A (as a tuple)
 
print(type(A.shape)) # here is the proof that the shape is a tuple
 
print(A.shape[0]) # the number of elements in the first dimension of A

6
(2, 3)
<class 'tuple'>
2


##  Important Methods

In [8]:
A = np.zeros((2, 3)) # creating an array of shape (2, 3)
 
A = A.reshape((3, 2)) # resize array A (3 rows, 2 columns)
A.ravel() # Flattens array A (one dimension only)
A.squeeze() # eliminates "1" dimensions from A.

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
A = np.zeros((2, 3)) # creating an array of shape (2, 3)
B = np.ones((2, 3)) # creating an array of shape (2, 3)

np.concatenate((A, B), axis=0) # axis 0: equivalent of np.vstack((A, B))

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.concatenate((A, B), axis=1) # axis 1: equivalent of np.hstack((A, B))

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])